"""
Django settings for taxipro project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = 'django-insecure-h=grwu1iy%6zs0qiib_t&4pgbe$i^*^koad_)4ec7s4-!g2yoq'

DEBUG = True

ALLOWED_HOSTS = ['ridexpress.in', 'www.ridexpress.in', 'localhost', '127.0.0.1']


CSRF_TRUSTED_ORIGINS = ['https://ridexpress.in', 'https://www.ridexpress.in']



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'superadmin',
    'adminuser',
    'rescue',
    'quality',
    'rest_framework',
    'telecaller',
    'distributer',
    'driver',
    'hr',
    'customer',
    'widget_tweaks',
    'tempus_dominus',
    'website',
    'author',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'superadmin.middleware.SuperAdminCheckMiddleware',
    'rescue.middleware.SuperAdminCheckMiddleware',
    'quality.middleware.SuperAdminCheckMiddleware',
    'distributer.middleware.distributerCheckMiddleware',
    'adminuser.middleware.SuperAdminCheckMiddleware',
    'telecaller.middleware.SuperAdminCheckMiddleware',
    
]

ROOT_URLCONF = 'taxipro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join('templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'taxipro.wsgi.application'

LOGIN_URL = '/login/'


DATABASES = {
       'default': {
           'ENGINE': 'djongo',
           'NAME': 'RideExpress',
           'USER': '',
           'PASSWORD': '',
           'HOST': 'localhost',
           'PORT': '27017',
       }
   }


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True



STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')
STATICFILES_DIRS= [
    os.path.join(BASE_DIR, 'static'),
]


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
